version: '3.8'

services:
  micro-cursos:
    build:
      context: ./micro-cursos
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sisdb2025
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TZ=America/Guayaquil # Ajustar la zona horaria de Ecuador
    networks:
      - host

  micro-estudiantes:
    build:
      context: ./micro-estudiantes
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sisdb2025
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TZ=America/Guayaquil # Ajustar la zona horaria de Ecuador
    networks:
      - host

  mysql:
    image: mysql:latest
    container_name: mysql-micro-spring
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "America/Guayaquil" #Ajustar a la zona horaria de Ecuador
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  mysql-data:
    driver: local
